/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SquaredWrapper */

#ifndef _Included_SquaredWrapper
#define _Included_SquaredWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SquaredWrapper
 * Method:    squared
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_montreuxclient_fastcv_SquaredWrapper_squared

  (JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_com_example_montreuxclient_fastcv_SquaredWrapper_analyze

  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
